### PR TITLE
feature 7436 - adding additional permissions to the Modernisation Pla…

### PR DESCRIPTION
**Pull request by Kudzai-moj**
## A reference to the issue / Description of it

[#7436](https://github.com/ministryofjustice/modernisation-platform/issues/7436)

## How does this PR fix the problem?

PR adds  specific create, update and delete permissions to the Modernisation Platform Engineering role which was previously read only. The role has the permissions, 

- Developer Additional Statements
- Instance Management
- Reporting Operations
- Fleet Manager

## How has this been tested?

Tested the update with a test role in cooker

## Deployment Plan / Instructions

Will this deployment impact the platform and / or services on it?

No

## Checklist (check `x` in `[ ]` of list items)

- [X] I have performed a self-review of my own code
- [x] All checks have passed
- [ ] I have made corresponding changes to the documentation
- [ ] Plan and discussed how it should be deployed to PROD (If needed)

## Additional comments (if any)

{Please write here}

### CODE REVIEW

**Review by ewastempel — CHANGES_REQUESTED** [review]
@Kudzai-moj we have discussed earlier that we will not allow what's in the deny list. This is not needed for this role, actions such as IAM and network related should be logged and therefore the use of admin role is appropriate here.

Keep it to the essential click-ops permissions only please.

**Review by ewastempel — DISMISSED** [review]
Looks great, thanks!

**Review by ewastempel — APPROVED** [review]
LGTM

**Comment by davidkelliott** [comment]
Closed these changes already appear to be in main.

**Pull request closed without merging**
