### PR TITLE
Amending hmpps-ems-moj-soc Access to EMS Shared Logging

### PR DESCRIPTION
**Pull request by jacobwoffenden**
Giving them administrator access to our shared logging account

### CODE REVIEW

**Comment by TomTucka** [comment]
Hi @jacobwoffenden 👋🏼 

Can I just ask why they need administrator access to the account?

**Comment by jacobwoffenden** [comment]
Hey @TomTucka

MOJ SOC need temporary administrative access to audit our logging infrastructure.

If we were doing this using our existing IAM setup, we'd assign them the InfraAdmin role.

If you're not happy with it, I could create a finer grained permission set, but as I mentioned, this is temporary. 

Cheers!

**Comment by TomTucka** [comment]
Hey @jacobwoffenden,

Sorry for the late response on this! 

I'd prefer us to start creating finer permissions by default even if access it's only temporary access. If you could have a crack at this that would be awesome, if you need a hand feel free to grab me.

**Comment by jacobwoffenden** [comment]
Hi @TomTucka,

Thanks for getting back to me. I've just given them access via our IAM account instead of SSO, so I will close this off.

**Pull request closed without merging**
